### PR TITLE
Updated SQL Saturday Minnesota website, added details

### PR DESCRIPTION
**Pull request by FultonAnalytics**
Initial sponsor details

### CODE REVIEW

**Comment by FultonAnalytics** [comment]
Apologies, im learning as I go. Ill be more cognizant as I maintain my indents

**Comment by way0utwest** [comment]
No worries, it's nothing I haven't done quite a bit. I did get the YAML extension for VSCode from Redhat. That helps me prevent a lot of silly mistakes.

**Comment by FultonAnalytics** [comment]
Just checking, is this something you already fixed quick or I need to go in and change?

Once I understand your process ill stop asking the silly questions 😃

**Comment by way0utwest** [comment]
It's easier if you change the code in your branch, which will update the PR. Indent the 3 lines and commit.

**Pull request merged**
